name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["task::bug"]
projects: ["instadeepai/21"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: intend
    attributes:
      label: What were you trying to do?
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: What did happen?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What were you expecting instead?
    validations:
      required: true
  - type: textarea
    id: more
    attributes:
      label: More context, logs, screenshots, how to reproduce the bug?
