name: CI

on:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  super-linter:
    permissions:
      contents: read # to fetch code (actions/checkout)
      checks: write # to mark the status of each individual linter run
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      -
        name: Lint Code Base
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_BASH: true
          VALIDATE_PHP_BUILTIN: true

          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  phpstan:
    name: PHPStan Static Analysis
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpstan@v3
      with:
        path: .
        memory_limit: 4G
